# Generated by Django 3.0.5 on 2020-04-21 18:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_blog', '0002_blogpost_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogPost',
            new_name='Post',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='publish',
            new_name='published',
        ),
    ]
